### PR TITLE
Remove trailing 'f' from data guide

### PR DESCRIPTION
**Pull request by mdlavin**
Minor fix

### CODE REVIEW

**Comment by brianleroux** [comment]
@mdlavin pls sign the cla so we can merge! 🙏

**Comment by mdlavin** [comment]
Signed. By the way arc.codes looks really nice and I can't wait to play with it. Thank you for making it available.

**Comment by mdlavin** [comment]
@brianleroux I signed the CLA

**Comment by brianleroux** [comment]
doh! thx for the ping ;)

**Pull request merged**
