### PR TITLE
Update data for current session / middleware / route API, other small changes

### PR DESCRIPTION
**Pull request by mikemaccana**
Minor change, but the other 'New Ops' stuff tends to be more advanced, sessions belongs with other basic topics.

### CODE REVIEW

**Comment by mikemaccana** [comment]
Updated Data guide too, fixing #71

**Comment by mikemaccana** [comment]
@brianleroux the build is pausing after `tape test/test.js | tap-spec` part, see https://travis-ci.com/arc-repos/arc.codes/builds/97969670 - I can't work out why, it completes successfully locally. Any ideas?

**Comment by brianleroux** [comment]
thx! sorry this took so long

**Comment by mikemaccana** [comment]
Woo! 😃 Did you find out what was up with the tests?

**Comment by brianleroux** [comment]
no idea actually…solved with patience! 😅

**Pull request merged**
